path:
  ckpt_path: "/content/gdrive/MyDrive/Colab Notebooks/honour_project/FastSpeech2/output3/ckpt/"
  log_path: "/content/gdrive/MyDrive/Colab Notebooks/honour_project/FastSpeech2/output3/log/"
  result_path: "/content/gdrive/MyDrive/Colab Notebooks/honour_project/FastSpeech2/output3/result/"
optimizer:
  batch_size: 4
  betas: [0.9, 0.98]
  eps: 0.000000001
  weight_decay: 0.01
  grad_clip_thresh: 1.0
  grad_acc_step: 1
  warm_up_step: 200
  anneal_steps: [1000, 2000, 3000]
  anneal_rate: 0.3
step:
  total_step: 4000
  log_step: 25
  synth_step: 100
  val_step: 100
  save_step: 500
